config/routes.rb
Rails.application.routes.draw do
  resources :administrators
  root "dishes#homepage"

  resources :dishes do
    collection do
      get "homepage"
    end
  end
  resources :ingredients
  resources :enterprises
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/dish.rb
class Dish < ApplicationRecord
  has_and_belongs_to_many :ingredients
  validates_presence_of :description, :price, :timePreparation
end

app/controllers/dishes_controller.rb
class DishesController < ApplicationController
  before_action :set_dish, only: [:show, :edit, :update, :destroy]

  # GET /dishes
  # GET /dishes.json
  def index
    @dishes = Dish.all.order(:description)
  end

  # GET /dishes/1
  # GET /dishes/1.json
  def show
  end

  def homepage
    @dishes = Dish.all.order(:description)
    @enterprises = Enterprise.all.limit(1)
  end

  # GET /dishes/new
  def new
    @dish = Dish.new
    @ingredients = Ingredient.all.order(:description)
  end

  # GET /dishes/1/edit
  def edit
    @ingredients = Ingredient.all.order(:description)
  end

  # POST /dishes
  # POST /dishes.json
  def create
    @dish = Dish.new(dish_params)

    respond_to do |format|
      if @dish.save
        format.html { redirect_to @dish, notice: 'Prato adicionado com sucesso!.' }
        format.json { render :show, status: :created, location: @dish }
      else
        format.html { render :new }
        format.json { render json: @dish.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dishes/1
  # PATCH/PUT /dishes/1.json
  def update
    respond_to do |format|
      if @dish.update(dish_params)
        format.html { redirect_to @dish, notice: 'Dish was successfully updated.' }
        format.json { render :show, status: :ok, location: @dish }
      else
        format.html { render :edit }
        format.json { render json: @dish.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dishes/1
  # DELETE /dishes/1.json
  def destroy
    @dish.destroy
    respond_to do |format|
      format.html { redirect_to dishes_url, notice: 'Dish was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dish
      @dish = Dish.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dish_params
      params.require(:dish).permit(:description, :price, :timePreparation, :ingredient_ids => [])
    end
end

app/helpers/dishes_helper.rb
module DishesHelper

end

app/views/dishes/_form.html.erb
<div class="col-6">
<%= form_with(model: dish, local: true) do |form| %>
  <% if dish.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(dish.errors.count, "error") %> prohibited this dish from being saved:</h2>

      <ul>
      <% dish.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label "Descrição" %>
    <%= form.text_field :description, id: :dish_description %>
  </div>

  <div class="field">
    <%= form.label "Preço $" %>
    <%= form.text_field :price, id: :dish_price %>
  </div>

  <div class="field">
    <%= form.label "Tempo de preparo horas:minutos" %>
    <%= form.time_select :timePreparation, id: :dish_timePreparation %>
  </div>

  <div class="field">
    <%= form.label "Ingredientes" %>
    <% @ingredients.each do|ingredient|%>
      <%= check_box_tag "dish[ingredient_ids][]", ingredient.id, @dish.ingredients.include?(ingredient) %>
      <%= ingredient.description %>
    <% end %>
  </div>

  <div class="actions">
    <%= form.submit "Salvar", :class => 'btn btn-outline-success' %>
  </div>

<% end %>
</div>

app/views/dishes/edit.html.erb
<h1>Editando prato: <span class="text-info"><%= @dish.description %></span></h1>

<%= render 'form', dish: @dish %>


<footer class="card-footer">

  <%= link_to 'Visualizar', @dish , :class => 'btn btn-outline-warning' %> |
  <%= link_to 'Voltar', dishes_path , :class => 'btn btn-outline-info' %>
</footer>

app/views/dishes/homepage.html.erb
<p id="notice"><%= notice %></p>
<header class="card-header-pills">
  <h1>
    <span class="text-center font-weight-bold efeito-titulo" id="titulo-home" style="font-size: 1.5em">
      <% @enterprises.each do |empresa| %>
        <%= empresa.name %>
        <% end  %>
    </span>
  </h1>
</header>

<div class="row">
  <% @dishes.each do |prato| %>
    <div class="col-4" style="  margin-bottom: 30px;">
      <div class="card">
        <div class="card-header text-center font-weight-bold">
          <%= prato.description %>
        </div>
        <div class="card-body">
          <div class="row text-center">
            <div class="col-4">
              Valor
            </div>
            <div class="col-8">
              Tempo de preparo
            </div>
            <div class="col-4">
              R<%= number_to_currency prato.price %>
            </div>
            <div class="col-8">
              <%= formatar_hora prato.timePreparation %>
            </div>
          </div>
        </div>
        <div id="btn-mod<%= prato.id %>" class="card-footer btn-outline-secondary text-center mais-info" onclick="modalShow('#mod<%= prato.id %>')">
          <span>Mais informações</span>
        </div>
      </div>
    </div>

<!--    modal-->

    <div class="modal" id="mod<%= prato.id %>" tabindex="-1" role="dialog">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header bg-light">
            <h4 class="modal-title"><%= prato.description %></h4>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close" onclick="modalHide('#mod<%= prato.id %>');">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            <p class="text-black-50">Ingredientes do prato:</p>
              <% prato.ingredients.order(:description).each do |ingrediente|  %>
                <p class="btn btn-dark disabled">
                  <%= ingrediente.description %>
                </p>
              <% end %>
          </div>
          <div class="modal-footer bg-light">
            <div class="row text-center">
              <div class="col-4">
                Valor
              </div>
              <div class="col-8">
                Tempo de preparo
              </div>
              <div class="col-4">
                R<%= number_to_currency prato.price %>
              </div>
              <div class="col-8">
                <%= formatar_hora prato.timePreparation %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>


<footer class="card-footer text-center text-primary font-weight-bold">
  <% @enterprises.each do |empresa| %>
    <span>
      <%= empresa.name %>
       - © Direitos Reservados
    </span><br>
    <p>
      <small>
        <%= empresa.address %> -
      </small>
      <span>
        <%= empresa.telephone %>
      </span>
      <small>
         - <%= empresa.email %>
      </small>
    </p>
  <% end %>
</footer>
<footer class="modal-footer">
  <%= link_to "Administrar conteúdo", administrators_path, :class => "btn btn-sm btn-light btnAdm"%>
</footer>
<script>
    $("#titulo-home").fitText();
</script>

app/views/dishes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pratos</h1>

<div class="row">
  <div class="col-3 btn-info">
    <p class="font-weight-bold">Descrição</p>
  </div>
  <div class="col-3 btn-info">
    <p class="font-weight-bold">Preço</p>
  </div>
  <div class="col-3 btn-info">
    <p class="font-weight-bold">Tempo de preparo</p>
  </div>
  <div class="col-3 btn-info">
    <p class="font-weight-bold">Ação</p>
  </div>
  <% @dishes.each do |dish| %>

      <div class="col-3 cel">
        <p><%= dish.description %> </p>
      </div>
      <div class="col-3">
        <p>R<%= number_to_currency dish.price %> </p>
      </div>
      <div class="col-3">
        <p><%= formatar_hora dish.timePreparation %> </p>
      </div>
      <div class="col-3">
        <span><%= link_to 'Exibir', dish, :class => 'btn btn-outline-info text-black-50' %></span>
        <span><%= link_to 'Editar', edit_dish_path(dish), :class => 'btn btn-outline-warning text-black-50' %></span>
        <span><%= link_to 'Excluir', dish, method: :delete, data: {confirm: 'Tem certeza que deseja excluir?'}, :class => 'btn btn-outline-danger text-black-50'%></span>

      </div>
    <p class="col-12"></p>
  <% end %>
</div>


<footer class="card-footer">
  <%= link_to 'Novo Prato', new_dish_path, :class => 'btn btn-outline-primary' %>
</footer>

<!--<script>-->
<!--  $('.cel').onmouseover(-->
<!--      $('p .col-12').addClass('btn-dark')-->
<!--  )-->
<!--</script>-->

app/views/dishes/new.html.erb
<h1>Novo Prato</h1>

<%= render 'form', dish: @dish %>
<div class="col-6">
  <%= link_to 'Voltar', dishes_path , :class => 'btn btn-outline-info'%>
</div>

app/views/dishes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
<!--  <strong>Descrição:</strong>-->
  <h1><%= @dish.description %></h1>
<hr>
</p>
<div class="row">
  <p class="col-3 card">
    <strong class="text-info card-header-pills">Preço:</strong>
  <span class="font-italic card-footer text-center text-black-50" style="font-size: 2.5em; border-radius: 0 0 15px 15px">

    R<%= number_to_currency(@dish.price) %>
  </span>
  </p>

  <p class="col-4 card">
    <strong class="card-header-pills text-info">Tempo de preparo:</strong>
    <span  class="font-italic card-footer text-center text-black-50" style="font-size: 2.5em; border-radius: 0 0 15px 15px">
      <%= formatar_hora @dish.timePreparation %>
    </span>

  </p>

  <p class="card col-5">
    <strong class="card-header-pills text-info">Ingredientes:</strong><br>
    <span class="card-footer" style="border-radius: 0 0 15px 15px">
      <% @dish.ingredients.order(:description).each do |ingredient|%>

        <span class="btn btn-secondary disabled " style="margin-bottom: 3px;">
          <%=ingredient.description%>
        </span>

      <%end%>
      </span>
  </p>

</div>

<footer class="card-footer">

<%= link_to 'Editar', edit_dish_path(@dish) , :class => 'btn btn-outline-warning' %> |
<%= link_to 'Voltar', dishes_path , :class => 'btn btn-outline-info' %>
</footer>