config/routes.rb
Rails.application.routes.draw do
  resources :administrators
  root "dishes#homepage"

  resources :dishes do
    collection do
      get "homepage"
    end
  end
  resources :ingredients
  resources :enterprises
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/administrator.rb
class Administrator < ApplicationRecord
end

app/controllers/administrators_controller.rb
class AdministratorsController < ApplicationController
  before_action :set_administrator, only: [:show, :edit, :update, :destroy]

  # GET /administrators
  # GET /administrators.json
  def index
    @administrators = Administrator.all
  end

  # GET /administrators/1
  # GET /administrators/1.json
  def show
  end

  # GET /administrators/new
  def new
    @administrator = Administrator.new
  end

  # GET /administrators/1/edit
  def edit
  end

  # POST /administrators
  # POST /administrators.json
  def create
    @administrator = Administrator.new(administrator_params)

    respond_to do |format|
      if @administrator.save
        format.html { redirect_to @administrator, notice: 'Administrator was successfully created.' }
        format.json { render :show, status: :created, location: @administrator }
      else
        format.html { render :new }
        format.json { render json: @administrator.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /administrators/1
  # PATCH/PUT /administrators/1.json
  def update
    respond_to do |format|
      if @administrator.update(administrator_params)
        format.html { redirect_to @administrator, notice: 'Administrator was successfully updated.' }
        format.json { render :show, status: :ok, location: @administrator }
      else
        format.html { render :edit }
        format.json { render json: @administrator.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /administrators/1
  # DELETE /administrators/1.json
  def destroy
    @administrator.destroy
    respond_to do |format|
      format.html { redirect_to administrators_url, notice: 'Administrator was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_administrator
      @administrator = Administrator.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def administrator_params
      params.require(:administrator).permit(:user, :password)
    end
end

app/helpers/administrators_helper.rb
module AdministratorsHelper
end

app/views/administrators/_form.html.erb
<%= form_with(model: administrator, local: true) do |form| %>
  <% if administrator.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(administrator.errors.count, "error") %> prohibited this administrator from being saved:</h2>

      <ul>
      <% administrator.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user %>
    <%= form.text_field :user, id: :administrator_user %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.text_field :password, id: :administrator_password %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/administrators/edit.html.erb
<h1>Editing Administrator</h1>

<%= render 'form', administrator: @administrator %>

<%= link_to 'Show', @administrator %> |
<%= link_to 'Back', administrators_path %>

app/views/administrators/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Área de Administração de conteúdo</h1>

<p>Acesse um dos menus acima para gerenciar o conteúdo de cada área.</p>

app/views/administrators/new.html.erb
<h1>New Administrator</h1>

<%= render 'form', administrator: @administrator %>

<%= link_to 'Back', administrators_path %>

app/views/administrators/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @administrator.user %>
</p>

<p>
  <strong>Password:</strong>
  <%= @administrator.password %>
</p>

<%= link_to 'Edit', edit_administrator_path(@administrator) %> |
<%= link_to 'Back', administrators_path %>